/**
 * ER | Ability to automatically transition an employee within a shift across locations in a group and across location groups in a district — Page Object
 *
 * Auto-generated by QA Pipeline Node 3
 * Feature: er_2600.feature
 * Team: SCH
 *
 * Locator Strategy (STRICT — built-in only):
 *   1. page.getByRole()        — explicit/implicit ARIA roles
 *   2. page.getByText()        — visible text content
 *   3. page.getByLabel()       — form control by label
 *   4. page.getByPlaceholder() — input by placeholder
 *   5. page.getByAltText()     — image by alt text
 *   6. page.getByTitle()       — element by title attribute
 *   7. page.getByTestId()      — element by data-testid
 *   BANNED: CSS selectors, XPath, hardcoded IDs, fragile selectors
 */

import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './ScheduleBasePage';
import { Logger } from '../utils/logger';

export class Er2600Page extends BasePage {

  // ─── Locators ──────────────────────────────────────────────

  private readonly locators = {
    // Navigation
    scheduleMenuItem: () =>
      this.page.getByRole('link', { name: 'Schedule' }),
    dashboardMenuItem: () =>
      this.page.getByRole('link', { name: 'Dashboard' }),

    // Auto-scheduler
    autoScheduleButton: () =>
      this.page.getByRole('button', { name: /auto.?schedule/i }),
    generateScheduleButton: () =>
      this.page.getByRole('button', { name: /generate/i }),
    confirmButton: () =>
      this.page.getByRole('button', { name: /confirm|ok|yes/i }),

    // Location & Group selectors
    locationSelector: () =>
      this.page.getByRole('combobox', { name: /location/i })
        .or(this.page.getByTestId('location-selector')),
    groupSelector: () =>
      this.page.getByRole('combobox', { name: /group/i })
        .or(this.page.getByTestId('group-selector')),
    districtSelector: () =>
      this.page.getByRole('combobox', { name: /district/i })
        .or(this.page.getByTestId('district-selector')),

    // Employee & Shift elements
    employeeRow: (name: string) =>
      this.page.getByRole('row', { name: new RegExp(name, 'i') }),
    shiftCell: (employee: string, day: string) =>
      this.page.getByTestId(`shift-${employee}-${day}`),
    transitionIndicator: () =>
      this.page.getByTestId('transition-indicator'),

    // Schedule view
    scheduleTable: () =>
      this.page.getByRole('table', { name: /schedule/i }),
    weekNavigator: () =>
      this.page.getByRole('navigation', { name: /week/i }),
    nextWeekButton: () =>
      this.page.getByRole('button', { name: /next/i }),

    // Status & messages
    successMessage: () =>
      this.page.getByRole('alert').filter({ hasText: /success/i }),
    errorMessage: () =>
      this.page.getByRole('alert').filter({ hasText: /error|fail/i }),
    loadingSpinner: () =>
      this.page.getByTestId('loading-spinner'),
  };

  constructor(page: Page) {
    super(page);
  }

  // ─── Navigation ────────────────────────────────────────────

  async navigateToSchedule(): Promise<void> {
    Logger.step('Navigating to Schedule page');
    await this.locators.scheduleMenuItem().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigateToDashboard(): Promise<void> {
    Logger.step('Navigating to Dashboard');
    await this.locators.dashboardMenuItem().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  // ─── Location & Group Selection ────────────────────────────

  async selectLocation(locationName: string): Promise<void> {
    Logger.step(`Selecting location: ${locationName}`);
    await this.locators.locationSelector().click();
    await this.page.getByRole('option', { name: locationName }).click();
  }

  async selectGroup(groupName: string): Promise<void> {
    Logger.step(`Selecting group: ${groupName}`);
    await this.locators.groupSelector().click();
    await this.page.getByRole('option', { name: groupName }).click();
  }

  async selectDistrict(districtName: string): Promise<void> {
    Logger.step(`Selecting district: ${districtName}`);
    await this.locators.districtSelector().click();
    await this.page.getByRole('option', { name: districtName }).click();
  }

  // ─── Auto-Scheduler ───────────────────────────────────────

  async runAutoScheduler(): Promise<void> {
    Logger.step('Running auto-scheduler');
    await this.locators.autoScheduleButton().click();
    await this.locators.confirmButton().click();
    await this.waitForScheduleGeneration();
  }

  async waitForScheduleGeneration(timeout: number = 120000): Promise<void> {
    Logger.step('Waiting for schedule generation to complete');
    await this.locators.loadingSpinner().waitFor({ state: 'hidden', timeout });
  }

  // ─── Shift & Transition Verification ───────────────────────

  async verifyEmployeeHasShift(employeeName: string): Promise<void> {
    Logger.step(`Verifying employee ${employeeName} has a shift assigned`);
    const row = this.locators.employeeRow(employeeName);
    await expect(row).toBeVisible();
  }

  async verifyTransitionExists(fromLocation: string, toLocation: string): Promise<void> {
    Logger.step(`Verifying transition from ${fromLocation} to ${toLocation}`);
    const indicator = this.locators.transitionIndicator();
    await expect(indicator).toBeVisible();
    await expect(indicator).toContainText(fromLocation);
    await expect(indicator).toContainText(toLocation);
  }

  async verifyNoTransitionForEmployee(employeeName: string): Promise<void> {
    Logger.step(`Verifying no transition for employee ${employeeName}`);
    const row = this.locators.employeeRow(employeeName);
    await expect(row).toBeVisible();
    const transition = row.getByTestId('transition-indicator');
    await expect(transition).toHaveCount(0);
  }

  async verifyShiftInSingleLocation(employeeName: string, location: string): Promise<void> {
    Logger.step(`Verifying ${employeeName} only scheduled in ${location}`);
    const row = this.locators.employeeRow(employeeName);
    await expect(row).toBeVisible();
    await expect(row).toContainText(location);
  }

  // ─── Schedule Metrics ──────────────────────────────────────

  async getScheduleCoverage(): Promise<number> {
    Logger.step('Getting schedule coverage percentage');
    const coverageEl = this.page.getByTestId('coverage-percentage');
    const text = await coverageEl.textContent();
    return parseFloat(text?.replace('%', '') || '0');
  }

  async getShiftCount(): Promise<number> {
    Logger.step('Getting total shift count');
    const rows = this.locators.scheduleTable().getByRole('row');
    return await rows.count() - 1; // subtract header
  }

  // ─── Assertions ────────────────────────────────────────────

  async verifySuccessMessage(): Promise<void> {
    await expect(this.locators.successMessage()).toBeVisible({ timeout: 10000 });
  }

  async verifyNoErrors(): Promise<void> {
    await expect(this.locators.errorMessage()).toHaveCount(0);
  }
}
