#!/usr/bin/env python3
"""
Node 7 — Bug Triage & Routing
Auto-labels, prioritizes, and creates bug reports for review.
Does NOT create bugs in Jira — creates local bug report files
for the QA Principal Engineer to review and approve before filing.

Input:  Analysis report from Node 6
Output: Bug reports in output/<team>/bugs/<story-id>/ for owner review
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
OUTPUT_BASE = "/Users/vshere/Documents/Projects/QAEndToEnd/output"
JIRA_URL = os.environ.get("JIRA_URL", "https://legiontech.atlassian.net")

COMPONENT_OWNERS = {
    "SCH-Schedule": "Schedule Team",
    "SCH-Shifts": "Schedule Team",
    "SCH-Locations": "Location Team",
    "SCH-Transitions": "Schedule Team",
    "SCH-Assignment": "Schedule Team",
    "SCH-General": "QA Team",
}


# ---------------------------------------------------------------------------
# Bug Report Generator
# ---------------------------------------------------------------------------

def create_bug_report(failure: dict, story_id: str, team: str, index: int) -> dict:
    """Create a detailed bug report for owner review."""

    severity = failure.get("severity", "major")
    component = failure.get("component", "SCH-General")
    classification = failure.get("classification", "true_failure")
    owner = COMPONENT_OWNERS.get(component, "QA Team")

    # Priority mapping
    priority_map = {
        "critical": "P0 - Blocker",
        "major": "P1 - High",
        "minor": "P2 - Medium",
        "trivial": "P3 - Low",
    }
    priority = priority_map.get(severity, "P2 - Medium")

    # Type mapping
    type_map = {
        "true_failure": "Bug",
        "flaky": "Flaky Test",
        "env_issue": "Environment Issue",
    }
    bug_type = type_map.get(classification, "Bug")

    bug_id = f"{story_id}-BUG-{index:03d}"

    return {
        "bug_id": bug_id,
        "story_id": story_id,
        "team": team,
        "status": "PENDING_REVIEW",
        "title": failure.get("title", "Test Failure"),
        "bug_type": bug_type,
        "severity": severity,
        "priority": priority,
        "component": component,
        "owner": owner,
        "classification": classification,
        "error_message": failure.get("error", "")[:500],
        "file": failure.get("file", ""),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "jira_url": f"{JIRA_URL}/browse/{story_id}",
        "review_actions": [
            "APPROVE — Create Jira bug ticket",
            "REJECT — False positive, close",
            "DEFER — Known issue, add to backlog",
            "REASSIGN — Route to different team",
        ],
    }


def generate_bug_markdown(bug: dict) -> str:
    """Generate human-readable bug report markdown."""
    lines = []
    lines.append(f"# Bug Report: {bug['bug_id']}")
    lines.append(f"")
    lines.append(f"**Status:** {bug['status']}")
    lines.append(f"**Action Required:** QA Principal Engineer review")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## Details")
    lines.append(f"")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Bug ID | {bug['bug_id']} |")
    lines.append(f"| Story | [{bug['story_id']}]({bug['jira_url']}) |")
    lines.append(f"| Team | {bug['team']} |")
    lines.append(f"| Type | {bug['bug_type']} |")
    lines.append(f"| Severity | {bug['severity']} |")
    lines.append(f"| Priority | {bug['priority']} |")
    lines.append(f"| Component | {bug['component']} |")
    lines.append(f"| Owner | {bug['owner']} |")
    lines.append(f"| Classification | {bug['classification']} |")
    lines.append(f"| Feature File | `{bug['file']}` |")
    lines.append(f"| Created | {bug['created_at'][:19]}Z |")
    lines.append(f"")
    lines.append(f"## Scenario")
    lines.append(f"**{bug['title']}**")
    lines.append(f"")
    lines.append(f"## Error")
    lines.append(f"```")
    lines.append(f"{bug['error_message']}")
    lines.append(f"```")
    lines.append(f"")
    lines.append(f"## Review Actions")
    lines.append(f"")
    for action in bug["review_actions"]:
        lines.append(f"- [ ] {action}")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Auto-generated by QA Pipeline Node 7 — Bug Triage & Routing*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Triage Summary
# ---------------------------------------------------------------------------

def generate_triage_summary(bugs: list, story_id: str, team: str) -> dict:
    """Generate triage summary for Slack notification."""
    by_type = {}
    by_severity = {}
    by_component = {}

    for bug in bugs:
        t = bug["bug_type"]
        by_type[t] = by_type.get(t, 0) + 1

        s = bug["severity"]
        by_severity[s] = by_severity.get(s, 0) + 1

        c = bug["component"]
        by_component[c] = by_component.get(c, 0) + 1

    return {
        "story_id": story_id,
        "team": team,
        "total_bugs": len(bugs),
        "by_type": by_type,
        "by_severity": by_severity,
        "by_component": by_component,
        "pending_review": len([b for b in bugs if b["status"] == "PENDING_REVIEW"]),
        "bugs": bugs,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Node 7 — Bug Triage & Routing")
    parser.add_argument("--story-id", required=True, help="Story ID (e.g., ER-2600)")
    parser.add_argument("--team", default="SCH", help="Team name")
    parser.add_argument("--analysis-report", required=True, help="Path to analysis-report.json from Node 6")
    parser.add_argument("--output-dir", default="", help="Output directory")
    args = parser.parse_args()

    # Set output dir
    if not args.output_dir:
        args.output_dir = os.path.join(OUTPUT_BASE, args.team, "bugs", args.story_id)
    os.makedirs(args.output_dir, exist_ok=True)

    print(f"{'='*50}")
    print(f"NODE 7 — Bug Triage & Routing")
    print(f"{'='*50}")
    print(f"Story ID: {args.story_id}")
    print(f"Team: {args.team}")
    print(f"Output: {args.output_dir}")
    print()

    # Load analysis report
    with open(args.analysis_report, "r") as f:
        report = json.load(f)

    # Collect all failures (true failures + flaky)
    fa = report.get("failure_analysis", {})
    all_failures = []
    all_failures.extend(fa.get("true_failures", []))
    all_failures.extend(fa.get("flaky_tests", []))

    if not all_failures:
        print("No failures found — no bugs to triage.")
        print(f"{'='*50}")
        print(f"NODE 7 — COMPLETE (no bugs)")
        print(f"{'='*50}")
        return

    # Step 1: Create bug reports
    print(f"Step 1: Creating {len(all_failures)} bug report(s)...")
    bugs = []
    for i, failure in enumerate(all_failures, 1):
        bug = create_bug_report(failure, args.story_id, args.team, i)
        bugs.append(bug)

        # Write individual bug report markdown
        md_content = generate_bug_markdown(bug)
        md_path = os.path.join(args.output_dir, f"{bug['bug_id']}.md")
        with open(md_path, "w") as f:
            f.write(md_content)

        # Write individual bug JSON
        json_path = os.path.join(args.output_dir, f"{bug['bug_id']}.json")
        with open(json_path, "w") as f:
            json.dump(bug, f, indent=2)

        icon = "BUG" if bug["bug_type"] == "Bug" else "FLAKY"
        print(f"  [{icon}] {bug['bug_id']} — {bug['title'][:60]}")
        print(f"         {bug['priority']} | {bug['component']} | {bug['owner']}")

    # Step 2: Generate triage summary
    print(f"\nStep 2: Generating triage summary...")
    summary = generate_triage_summary(bugs, args.story_id, args.team)

    summary_path = os.path.join(args.output_dir, f"{args.story_id}-triage-summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    # Step 3: Generate review index
    print(f"\nStep 3: Generating review index...")
    index_lines = []
    index_lines.append(f"# Bug Triage — {args.story_id}")
    index_lines.append(f"")
    index_lines.append(f"**Team:** {args.team} | **Total Bugs:** {len(bugs)} | **Status:** PENDING REVIEW")
    index_lines.append(f"")
    index_lines.append(f"Review each bug below and mark your decision:")
    index_lines.append(f"- APPROVE — Create Jira ticket")
    index_lines.append(f"- REJECT — False positive")
    index_lines.append(f"- DEFER — Known issue, backlog")
    index_lines.append(f"- REASSIGN — Route to different team")
    index_lines.append(f"")
    index_lines.append(f"---")
    index_lines.append(f"")
    index_lines.append(f"| # | Bug ID | Type | Severity | Priority | Component | Title |")
    index_lines.append(f"|---|--------|------|----------|----------|-----------|-------|")
    for i, bug in enumerate(bugs, 1):
        title = bug['title'][:50]
        index_lines.append(f"| {i} | [{bug['bug_id']}]({bug['bug_id']}.md) | {bug['bug_type']} | {bug['severity']} | {bug['priority']} | {bug['component']} | {title} |")
    index_lines.append(f"")
    index_lines.append(f"---")
    index_lines.append(f"*Generated by QA Pipeline Node 7 — Bug Triage & Routing*")

    index_path = os.path.join(args.output_dir, f"{args.story_id}-bug-review-index.md")
    with open(index_path, "w") as f:
        f.write("\n".join(index_lines))

    # Print summary
    print(f"\n--- Triage Summary ---")
    print(f"Total bugs: {summary['total_bugs']}")
    print(f"By type: {summary['by_type']}")
    print(f"By severity: {summary['by_severity']}")
    print(f"By component: {summary['by_component']}")
    print(f"Pending review: {summary['pending_review']}")

    print(f"\nFiles created in: {args.output_dir}")
    for f in sorted(os.listdir(args.output_dir)):
        print(f"  {f}")

    print(f"\n{'='*50}")
    print(f"NODE 7 — COMPLETE")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
