#!/usr/bin/env node

/**
 * Rerun Failed Scenarios
 *
 * Reruns scenarios from a rerun file generated by merge-reports.js
 *
 * Usage:
 *   node scripts/rerun-failed.js [options]
 *
 * Options:
 *   --rerun-file <path>    Path to rerun file (default: reports/rerun.txt)
 *   --retries <number>     Number of retries (default: 1)
 *   --workers <number>     Number of workers (default: 5)
 *   --headed               Run in headed mode
 *   --verbose              Verbose output
 *
 * Examples:
 *   # Rerun failed tests
 *   node scripts/rerun-failed.js
 *
 *   # Rerun with custom file and more retries
 *   node scripts/rerun-failed.js --rerun-file custom-rerun.txt --retries 3
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

// ============================================================================
// Configuration
// ============================================================================

class RerunConfig {
  constructor() {
    this.rerunFile = this.getArg('--rerun-file', 'reports/rerun.txt');
    this.retries = this.getArg('--retries', 1);
    this.workers = this.getArg('--workers', 5);
    this.headed = this.hasFlag('--headed');
    this.verbose = this.hasFlag('--verbose') || this.hasFlag('-v');

    this.rootDir = path.join(__dirname, '..');
    this.rerunFilePath = path.join(this.rootDir, this.rerunFile);
  }

  getArg(name, defaultValue) {
    const index = process.argv.indexOf(name);
    if (index === -1) return defaultValue;

    const value = process.argv[index + 1];
    if (!value || value.startsWith('--')) return defaultValue;

    const num = Number(value);
    return isNaN(num) ? value : num;
  }

  hasFlag(name) {
    return process.argv.includes(name);
  }
}

// ============================================================================
// Rerun Executor
// ============================================================================

class RerunExecutor {
  constructor(config) {
    this.config = config;
  }

  /**
   * Execute rerun
   */
  async execute() {
    console.log('🔄 Rerunning Failed Scenarios\n');
    this.printConfig();

    // Check if rerun file exists
    if (!fs.existsSync(this.config.rerunFilePath)) {
      console.error(`❌ Rerun file not found: ${this.config.rerunFilePath}`);
      console.log('\nGenerate rerun file first:');
      console.log('  node scripts/merge-reports.js --capture-failures\n');
      return false;
    }

    // Read rerun file
    const rerunContent = fs.readFileSync(this.config.rerunFilePath, 'utf-8');
    const testPaths = rerunContent.split('\n').filter(line => line.trim());

    if (testPaths.length === 0) {
      console.log('✅ No failed tests to rerun');
      return true;
    }

    console.log(`Found ${testPaths.length} failed tests to rerun\n`);

    // Build Playwright command
    const args = this.buildPlaywrightArgs(testPaths);

    console.log('Executing rerun...\n');

    if (this.config.verbose) {
      console.log(`Command: npx playwright test ${args.join(' ')}\n`);
    }

    // Execute Playwright
    const success = await this.executePlaywright(args);

    if (success) {
      console.log('\n✅ All failed tests passed on rerun!');
    } else {
      console.log('\n❌ Some tests still failing after rerun');
    }

    return success;
  }

  /**
   * Build Playwright CLI arguments
   */
  buildPlaywrightArgs(testPaths) {
    const args = [];

    // Add test paths
    args.push(...testPaths);

    // Configuration
    args.push(`--workers=${this.config.workers}`);
    args.push(`--retries=${this.config.retries}`);

    if (this.config.headed) {
      args.push('--headed');
    }

    // Use list reporter for rerun
    args.push('--reporter=list,html');

    return args;
  }

  /**
   * Execute Playwright command
   */
  async executePlaywright(args) {
    return new Promise((resolve) => {
      const child = spawn('npx', ['playwright', 'test', ...args], {
        cwd: this.config.rootDir,
        stdio: 'inherit',
      });

      child.on('close', (exitCode) => {
        resolve(exitCode === 0);
      });

      child.on('error', (error) => {
        console.error('Error executing Playwright:', error.message);
        resolve(false);
      });
    });
  }

  /**
   * Print configuration
   */
  printConfig() {
    console.log('Configuration:');
    console.log(`  Rerun File: ${this.config.rerunFile}`);
    console.log(`  Workers:    ${this.config.workers}`);
    console.log(`  Retries:    ${this.config.retries}`);
    console.log(`  Headed:     ${this.config.headed}`);
    console.log('');
  }
}

// ============================================================================
// Main Execution
// ============================================================================

async function main() {
  const config = new RerunConfig();
  const executor = new RerunExecutor(config);

  const success = await executor.execute();

  process.exit(success ? 0 : 1);
}

// Run if executed directly
if (require.main === module) {
  main().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

module.exports = { RerunExecutor, RerunConfig };
