/**
 *  — Step Definitions
 *
 * Auto-generated by QA Pipeline Node 3
 * Feature: er_2600.feature
 * Team: SCH
 */

import { createBdd } from 'playwright-bdd';
import { test, expect } from '../../../src/fixtures/test-fixtures';
import { Er2600Page } from '../pages/Er2600Page';
import { Logger } from '../utils/logger';

const { Given, When, Then } = createBdd(test);

// ─── Context Keys ────────────────────────────────────────────
const CTX = {
  SCHEDULE_GENERATED: 'scheduleGenerated',
  TRANSITION_CREATED: 'transitionCreated',
  EMPLOYEE_QUALIFIED: 'employeeQualified',
};
